services:
  pindar-fe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    container_name: pindar-fe
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
